# Generated by Django 5.1.5 on 2025-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6, verbose_name='Стоимость доставки'),
        ),
    ]
