# Generated by Django 5.1.5 on 2025-03-27 17:07

from django.db import migrations

def forwards(apps, schema_editor):
    Dish = apps.get_model('restaurants', 'Dish')
    Category = apps.get_model('restaurants', 'Category')
    
    # Назначьте категории для существующих блюд
    for dish in Dish.objects.filter(category__isnull=True):
        dish.category = Category.objects.first()
        dish.save()

class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0004_previous_migration'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]