# Generated by Django 5.1.5 on 2025-02-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
